# Flux Controller Metrics Collection
#
# Flux controllers expose metrics on port 8080 (http-prom) but their services
# only expose HTTP port 80. Therefore, we use PodMonitor to collect metrics
# directly from controller pods rather than through services.
#
# Controllers monitored:
# - source-controller: Git/OCI repository management
# - kustomize-controller: Kustomization reconciliation
# - helm-controller: Helm release management
# - notification-controller: Event notifications
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers-pods
  namespace: monitoring
  labels:
    app.kubernetes.io/name: flux-controllers-pods
    app.kubernetes.io/instance: flux-controllers-pods
    app.kubernetes.io/part-of: flux
    monitoring.k3s-flux.io/component: flux-metrics
spec:
  # Monitor all Flux controller pods directly
  # (including those without services)
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - source-controller
          - kustomize-controller
          - helm-controller
          - notification-controller
  podMetricsEndpoints:
    # Metrics endpoint for all Flux controllers
    - port: http-prom
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        # Add controller name from pod labels
        - sourceLabels: [__meta_kubernetes_pod_label_app]
          targetLabel: controller
        # Add namespace
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        # Add pod information
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        # Add cluster label
        - targetLabel: cluster
          replacement: k3s-flux
      metricRelabelings:
        # Keep only relevant Flux metrics to reduce cardinality
        - sourceLabels: [__name__]
          regex: "flux_.*|gotk_.*|controller_runtime_.*|workqueue_.*|rest_client_.*"
          action: keep
