apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-core-grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-core
        namespace: monitoring
      interval: 1h
  install:
    createNamespace: false
    disableWait: false
    timeout: 3m
    remediation:
      retries: 2
  upgrade:
    remediation:
      remediateLastFailure: true
    timeout: 3m
  values:
    # Admin credentials from secret
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password

    # Ephemeral storage - no persistence
    persistence:
      enabled: false

    # Resource limits for core Grafana
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Data sources
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus-Core
            type: prometheus
            url: http://monitoring-core-prometheus-prometheus:9090
            access: proxy
            isDefault: true
            editable: true

    # Dashboard providers - load from ConfigMaps
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: "longhorn"
            orgId: 1
            folder: "Longhorn"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/longhorn
          - name: "flux"
            orgId: 1
            folder: "Flux"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/flux
          - name: "nodes"
            orgId: 1
            folder: "Node Monitoring"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/nodes

    # Sidecar configuration to load dashboards from ConfigMaps
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /tmp/dashboards
        searchNamespace: monitoring
        provider:
          foldersFromFilesStructure: true

    # Essential dashboards loaded from ConfigMaps
    dashboards:
      default:
        kubernetes-cluster:
          gnetId: 7249
          revision: 1
          datasource: Prometheus-Core
        kubernetes-pods:
          gnetId: 6336
          revision: 1
          datasource: Prometheus-Core
        node-exporter:
          gnetId: 1860
          revision: 37
          datasource: Prometheus-Core
        gitops-health:
          file: gitops-health-dashboard.json
          datasource: Prometheus-Core
        k3s2-node-monitoring:
          file: k3s2-node-dashboard.json
          datasource: Prometheus-Core
        multi-node-cluster-overview:
          file: multi-node-cluster-dashboard.json
          datasource: Prometheus-Core
      longhorn:
        longhorn-dashboard:
          url: https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/deploy/longhorn-grafana-dashboard.json
          datasource: Prometheus-Core
      flux:
        flux-cluster:
          gnetId: 16714
          revision: 1
          datasource: Prometheus-Core
        flux-control-plane:
          gnetId: 16713
          revision: 1
          datasource: Prometheus-Core
      nodes:
        k3s2-node-dashboard:
          file: k3s2-node-dashboard.json
          datasource: Prometheus-Core

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 472
      fsGroup: 472

    # Disable unnecessary features for core setup
    imageRenderer:
      enabled: false

    # Environment variables
    env:
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: ""
