apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Core monitoring - ephemeral, bulletproof
resources:
  - namespace.yaml
  - helm-repository.yaml
  - prometheus-core.yaml
  - grafana-core.yaml
  - servicemonitor.yaml

# Common labels for core monitoring
commonLabels:
  app.kubernetes.io/name: monitoring-core
  app.kubernetes.io/instance: monitoring-core
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: k3s-flux
  monitoring.k3s-flux.io/tier: core

# Name prefix for core resources
namePrefix: monitoring-core-

# Set the namespace
namespace: monitoring
