# Update Detection Configuration
# This file configures the behavior of the update detection system

# Global settings
global:
  # How often to run update detection (cron format)
  schedule: "0 6 * * *" # Daily at 6 AM

  # Default output format for reports
  default_output_format: "json"

  # Enable/disable notifications
  notifications_enabled: true

  # Retention period for update history (days)
  history_retention_days: 90

# Component-specific configuration
components:
  k3s:
    # Which release channel to track
    channel: "stable"

    # How often to check for updates (hours)
    check_interval: 24

    # Minimum version to consider (for security)
    minimum_version: "v1.28.0"

    # Skip pre-release versions
    skip_prereleases: true

    # GitHub API settings
    github_repo: "k3s-io/k3s"
    api_timeout: 30

  flux:
    # Track individual controllers or meta-releases
    track_controllers: true

    # Check interval (hours)
    check_interval: 24

    # Skip pre-release versions
    skip_prereleases: true

    # Controller repositories to track
    controllers:
      source-controller: "fluxcd/source-controller"
      kustomize-controller: "fluxcd/kustomize-controller"
      helm-controller: "fluxcd/helm-controller"
      notification-controller: "fluxcd/notification-controller"

    # Main Flux repository for meta-releases
    main_repo: "fluxcd/flux2"

    # API timeout
    api_timeout: 30

  longhorn:
    # Check interval (hours)
    check_interval: 24

    # Minimum version to consider
    minimum_version: "v1.9.0"

    # Skip pre-release versions
    skip_prereleases: true

    # GitHub repository
    github_repo: "longhorn/longhorn"

    # Helm repository URL
    helm_repo_url: "https://charts.longhorn.io"

    # API timeout
    api_timeout: 30

    # Storage health check before updates
    check_storage_health: true

  helm:
    # Check interval (hours)
    check_interval: 24

    # Skip pre-release versions
    skip_prereleases: true

    # Timeout for helm operations
    helm_timeout: 60

    # Maximum number of releases to process
    max_releases: 100

    # Check dependencies for changes
    check_dependencies: true

# Notification settings
notifications:
  # Critical updates (security, breaking changes)
  critical_updates:
    enabled: true
    methods: ["log", "file"]

  # Regular updates
  regular_updates:
    enabled: false
    methods: ["log"]

  # Update completion notifications
  completion_notifications:
    enabled: true
    methods: ["log", "file"]

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARN, ERROR
  level: "INFO"

  # Log format: text, json
  format: "text"

  # Enable timestamps
  timestamps: true

  # Log file rotation
  rotation:
    enabled: true
    max_size_mb: 10
    max_files: 5
    max_age_days: 30

# Report generation settings
reporting:
  # Default formats to generate
  default_formats: ["json"]

  # Include update history in reports
  include_history: false

  # Report storage location
  storage_path: "reports"

  # Compress old reports
  compress_old_reports: true

  # Report retention (days)
  retention_days: 90

# Security settings
security:
  # Validate SSL certificates for API calls
  verify_ssl: true

  # GitHub API rate limiting
  github_api_rate_limit: 60

  # Timeout for all HTTP requests
  http_timeout: 30

  # User agent for API requests
  user_agent: "k3s-flux-update-detector/1.0"

# Advanced settings
advanced:
  # Parallel processing of components
  parallel_processing: true

  # Maximum concurrent API requests
  max_concurrent_requests: 5

  # Retry settings for failed requests
  retry:
    max_attempts: 3
    backoff_multiplier: 2
    initial_delay: 1
