apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-disk-discovery
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn-disk-discovery
    app.kubernetes.io/part-of: k3s-flux
    app.kubernetes.io/component: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-disk-discovery
  labels:
    app.kubernetes.io/name: longhorn-disk-discovery
    app.kubernetes.io/part-of: k3s-flux
    app.kubernetes.io/component: infrastructure
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-disk-discovery
  labels:
    app.kubernetes.io/name: longhorn-disk-discovery
    app.kubernetes.io/part-of: k3s-flux
    app.kubernetes.io/component: infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-disk-discovery
subjects:
  - kind: ServiceAccount
    name: longhorn-disk-discovery
    namespace: longhorn-system
