apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Storage components - can fail without breaking core
  - ../longhorn/base/
  - disk-discovery-daemonset.yaml
  - ../k3s1-node-config/
  # Uncomment when k3s2 joins the cluster
  # - ../k3s2-node-config/
  
# If Longhorn is being a pain in the ass, this fails gracefully
# Your core infrastructure and containers keep working