apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: example-app
  app.kubernetes.io/part-of: example-app
  app.kubernetes.io/managed-by: flux
