apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all resource files in the base directory
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml

# Note: Avoiding commonLabels to prevent immutable field conflicts with deployment selectors
# Labels are applied directly in the resource manifests instead

# Common annotations
commonAnnotations:
  fluxcd.io/reconcile: "10s"

# Name prefix for all resources
namePrefix: example-app-

# Default namespace (can be overridden in overlays)
namespace: example-app
