apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all resource files in the base directory
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - missing-file.yaml

# Common labels to be applied to all resources
commonLabels:
  app.kubernetes.io/name: example-app
  app.kubernetes.io/part-of: example-app
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/component: backend

# Common annotations
commonAnnotations:
  fluxcd.io/reconcile: "10s"

# Name prefix for all resources
namePrefix: example-app-

# Default namespace (can be overridden in overlays)
namespace: example-app
