apiVersion: v1
kind: Service
metadata:
  name: longhorn-test
  labels:
    app: longhorn-test
    app.kubernetes.io/name: longhorn-test
    app.kubernetes.io/part-of: storage-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: longhorn-test
  type: ClusterIP
