apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-community
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: monitoring
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
