apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# CRDs must be installed first
resources:
  - namespace.yaml
  - grafana-base-secret.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - servicemonitor.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: monitoring
  app.kubernetes.io/instance: monitoring
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: k3s-flux

# Name prefix for all resources
namePrefix: monitoring-

# Set the namespace for all resources
namespace: monitoring
