apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
patches:
  - target:
      kind: Node
      name: k3s1
    patch: |-
      - op: add
        path: /metadata/annotations/node.longhorn.io~1paths
        value: "/mnt/longhorn/sdh1"
