apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.8.3"  # Upgrade to 1.8.3 as next step in sequential upgrade
      sourceRef:
        kind: HelmRepository
        name: longhorn-longhorn  # Updated to match the actual HelmRepository name
        namespace: longhorn-system
      interval: 1h
  values:
    # Configure Longhorn settings
    defaultSettings:
      # Storage settings
      defaultClass: true
      defaultDataPath: /var/lib/longhorn/
      defaultReplicaCount: 2
      defaultDataLocality: best-effort
      
      # Resource management
      guaranteedEngineManagerCpu: 15  # 15% of system CPU
      guaranteedReplicaManagerCpu: 15  # 15% of system CPU
      
      # Disk and node configuration
      createDefaultDiskLabeledNodes: true
      defaultDiskSelector: ["storage=longhorn"]
      
      # Replica and backup settings
      replicaAutoBalance: best-effort
      replicaSoftAntiAffinity: true
      replicaZoneSoftAntiAffinity: true
      replicaReplenishmentWaitInterval: 600  # 10 minutes
      concurrentReplicaRebuildPerNodeLimit: 5
      concurrentVolumeBackupRestorePerNodeLimit: 5
      
      # Backup configuration
      backupTarget: ""
      backupTargetCredentialSecret: ""
      backupstorePollInterval: 300  # 5 minutes
      
      # Job settings
      recurringJobSelector: ["longhorn=backup"]
      allowRecurringJobWhileVolumeDetached: true
      
      # Node and volume settings
      nodeDownPodDeletionPolicy: do-nothing
      allowVolumeCreationWithDegradedAvailability: true
      
      # System settings
      systemManagedPodsImagePullPolicy: IfNotPresent
      autoCleanupSystemGeneratedSnapshot: true
    
    # Configure persistence
    persistence:
      defaultClass: true
      defaultFsType: ext4
      reclaimPolicy: Delete
    
    # Configure the UI
    service:
      ui:
        type: ClusterIP
        nodePort: null
        annotations: {}
