apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds/longhorn-crd.yaml
  - helm-repository.yaml
  - helm-release.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: longhorn
  app.kubernetes.io/instance: longhorn
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: k3s-flux

# Name prefix for all resources
namePrefix: longhorn-

# Set the namespace for all resources
namespace: longhorn-system
