apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds/longhorn-crd.yaml
  - helm-repository.yaml
  - helm-release.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: longhorn
  app.kubernetes.io/instance: longhorn
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: k3s-flux

# Note: Removed namePrefix and namespace settings to avoid conflicts
# The namespace is explicitly defined in namespace.yaml
# HelmRelease resources should not have name prefixes
