apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds/longhorn-crd.yaml
  - helm-repository.yaml
  - helm-release.yaml

# Note: Removed commonLabels to avoid conflicts with Helm-managed resources
# HelmRelease should not have commonLabels applied as it interferes with Helm's labeling
# Labels are managed by Helm chart and individual resource metadata instead

# Note: Removed namePrefix and namespace settings to avoid conflicts
# The namespace is explicitly defined in namespace.yaml
# HelmRelease resources should not have name prefixes
