apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include the base configuration
resources:
  - ../../base

# Override the namespace
namespace: example-app-staging

# Set environment-specific labels
commonLabels:
  environment: staging
  app.kubernetes.io/environment: staging

# Patch the deployment for staging
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/strategy/type
        value: RollingUpdate
      - op: add
        path: /spec/strategy/rollingUpdate
        value:
          maxSurge: 1
          maxUnavailable: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 192Mi
    target:
      kind: Deployment
      name: example-app

# Add staging-specific configurations
configMapGenerator:
  - name: example-app-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=debug
      - FEATURE_FLAG_CACHE_ENABLED=true
