apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app
  namespace: flux-system
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/part-of: example-app
    app.kubernetes.io/managed-by: flux
spec:
  interval: 5m
  path: ./apps/example-app/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 2m
