apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
  dependsOn:
    - name: infrastructure-core
      namespace: flux-system
  # Storage can fail without breaking core infrastructure