apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k3s2-longhorn-disks
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/k3s2-node-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  dependsOn:
    - name: infrastructure-storage
      namespace: flux-system
