apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Application resources
  - example-app-kustomization.yaml

  # Top-level Kustomization CRs for infra and monitoring
  - infrastructure.yaml
  - monitoring.yaml
