apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CRDs first
  - ../../infrastructure/monitoring/crds/
  
  # Application resources
  - example-app-kustomization.yaml
  - apps-longhorn-test-dev.yaml
  
  # Infrastructure components
  - ../../infrastructure/namespace.yaml
  - ../../infrastructure/nginx-ingress/
  - ../../infrastructure/longhorn/base/
  - ../../infrastructure/namespaces/storage-test-namespace.yaml
  - ../../infrastructure/monitoring/base/
