apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: infrastructure
  labels:
    app: default-backend
    app.kubernetes.io/part-of: infrastructure
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: default-backend
