apiVersion: v1
kind: Secret
metadata:
  name: grafana-longterm-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: REPLACE_WITH_SECURE_PASSWORD_LONGTERM
