apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k3s2-node.yaml
patches:
  - target:
      kind: Node
      name: k3s2
    patch: |-
      - op: add
        path: /metadata/annotations/node.longhorn.io~1paths
        value: "/mnt/longhorn/sdb1"