apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '75.6.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1h
  values:
    # Install CRDs
    crds:
      create: true
    
    # Disable default alertmanager and prometheus instances
    alertmanager:
      enabled: false
    prometheus:
      enabled: false
    
    # Enable only the operator and CRDs
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    nodeExporter:
      enabled: false
    kubeStateMetrics:
      enabled: false
    prometheusOperator:
      enabled: true
      serviceMonitor:
        selfMonitor: false
    
    # Disable default dashboards and rules
    defaultRules:
      create: false
    grafana:
      enabled: false
