apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Core networking and ingress - NO STORAGE DEPENDENCIES
  - ../nginx-ingress/
  - ../namespace.yaml
  
# These services work WITHOUT storage
# Your containers will ALWAYS be able to deploy