apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/example-app/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  timeout: 2m
  dependsOn:
    - name: flux-system  # Wait for the main flux-system kustomization
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: example-app
      namespace: example-app-dev
