apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: monitoring
  app.kubernetes.io/instance: monitoring
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: k3s-flux
