apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: infrastructure
  labels:
    app: default-backend
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: flux
  template:
    metadata:
      labels:
        app: default-backend
        app.kubernetes.io/part-of: infrastructure
        app.kubernetes.io/managed-by: flux
    spec:
      containers:
      - name: default-backend
        image: k8s.gcr.io/defaultbackend-amd64:1.5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: infrastructure
  labels:
    app: default-backend
    app.kubernetes.io/part-of: infrastructure
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: default-backend
