apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  values:
    controller:
      # Disable the default backend that comes with the chart
      defaultBackend:
        enabled: false
      # Configure the default backend service
      defaultBackendService: infrastructure/default-backend
