apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      # Enable metrics for Prometheus
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
    # Default backend configuration
    defaultBackend:
      enabled: true
      name: default-backend
      image:
        repository: k8s.gcr.io/defaultbackend-amd64
        tag: "1.5"
        pullPolicy: IfNotPresent
