apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - release.yaml
  - default-backend.yaml

# Patch the HelmRelease to use our custom default backend
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: nginx-ingress
