apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0"  # Using a specific version for stability
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: infrastructure
      interval: 1m
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
        externalTrafficPolicy: Local
      metrics:
        enabled: false  # Disable metrics since we don't have Prometheus Operator yet
      # Configure default backend
      defaultBackend:
        enabled: true
        name: default-backend
        port:
          number: 80
      # Required for K3s
      kubeletPath: /var/lib/rancher/agent/kubelet/standalone/kubelet.sock
