apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
  - namespace.yaml
  # Infrastructure components
  - nginx-ingress/
  # - cert-manager/
  # - monitoring/
  # - storage/
  # Example application
  - ../apps/example-app/

commonLabels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/managed-by: flux

# Add common annotations if needed
# commonAnnotations:
#   argocd.argoproj.io/sync-wave: "-1"
