apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: Do not set namespace here as it causes conflicts with sub-kustomizations

resources:
  - namespace.yaml
  # Infrastructure components
  - nginx-ingress/
  - longhorn/base/
  - tailscale/base/
  # - cert-manager/
# Note: Removed commonLabels to avoid conflicts with HelmRelease resources
# HelmReleases manage their own labeling and commonLabels cause immutable field conflicts
# Individual components can add their own labels as needed

# Add common annotations if needed
# commonAnnotations:
#   argocd.argoproj.io/sync-wave: "-1"
